-- CO (Customer Orders) - tables, identity columns, JSON, primary/unique/check constraints.
-- Ported from Oracle co_create.sql.
--   Oracle "INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY" -> "integer GENERATED BY DEFAULT AS IDENTITY"
--   Oracle BLOB (product_details, holding JSON) -> jsonb ; other BLOBs -> bytea
--   Oracle VARCHAR2(n CHAR) -> varchar(n)
-- Foreign keys and secondary indexes are added after data load (03_indexes_constraints.sql).
SET search_path TO co, public;

CREATE TABLE customers (
    customer_id   integer GENERATED BY DEFAULT AS IDENTITY,
    email_address varchar(255) NOT NULL,
    full_name     varchar(255) NOT NULL,
    CONSTRAINT customers_pk      PRIMARY KEY (customer_id),
    CONSTRAINT customers_email_u UNIQUE (email_address)
);

CREATE TABLE stores (
    store_id          integer GENERATED BY DEFAULT AS IDENTITY,
    store_name        varchar(255) NOT NULL,
    web_address       varchar(100),
    physical_address  varchar(512),
    latitude          numeric(9,6),
    longitude         numeric(9,6),
    logo              bytea,
    logo_mime_type    varchar(512),
    logo_filename     varchar(512),
    logo_charset      varchar(512),
    logo_last_updated date,
    CONSTRAINT stores_pk     PRIMARY KEY (store_id),
    CONSTRAINT store_name_u  UNIQUE (store_name),
    CONSTRAINT store_at_least_one_address_c
        CHECK (web_address IS NOT NULL OR physical_address IS NOT NULL)
);

CREATE TABLE products (
    product_id         integer GENERATED BY DEFAULT AS IDENTITY,
    product_name       varchar(255) NOT NULL,
    unit_price         numeric(10,2),
    product_details    jsonb,          -- Oracle: BLOB with CHECK (product_details is json)
    product_image      bytea,
    image_mime_type    varchar(512),
    image_filename     varchar(512),
    image_charset      varchar(512),
    image_last_updated date,
    CONSTRAINT products_pk PRIMARY KEY (product_id)
);

CREATE TABLE orders (
    order_id     integer GENERATED BY DEFAULT AS IDENTITY,
    order_tms    timestamp    NOT NULL,
    customer_id  integer      NOT NULL,
    order_status varchar(10)  NOT NULL,
    store_id     integer      NOT NULL,
    CONSTRAINT orders_pk PRIMARY KEY (order_id),
    CONSTRAINT orders_status_c CHECK (order_status IN
        ('CANCELLED','COMPLETE','OPEN','PAID','REFUNDED','SHIPPED'))
);

CREATE TABLE shipments (
    shipment_id      integer GENERATED BY DEFAULT AS IDENTITY,
    store_id         integer      NOT NULL,
    customer_id      integer      NOT NULL,
    delivery_address varchar(512) NOT NULL,
    shipment_status  varchar(100) NOT NULL,
    CONSTRAINT shipments_pk PRIMARY KEY (shipment_id),
    CONSTRAINT shipment_status_c CHECK (shipment_status IN
        ('CREATED','SHIPPED','IN-TRANSIT','DELIVERED'))
);

CREATE TABLE order_items (
    order_id     integer      NOT NULL,
    line_item_id integer      NOT NULL,
    product_id   integer      NOT NULL,
    unit_price   numeric(10,2) NOT NULL,
    quantity     integer      NOT NULL,
    shipment_id  integer,
    CONSTRAINT order_items_pk        PRIMARY KEY (order_id, line_item_id),
    CONSTRAINT order_items_product_u UNIQUE (product_id, order_id)
);

CREATE TABLE inventory (
    inventory_id      integer GENERATED BY DEFAULT AS IDENTITY,
    store_id          integer NOT NULL,
    product_id        integer NOT NULL,
    product_inventory integer NOT NULL,
    CONSTRAINT inventory_pk PRIMARY KEY (inventory_id),
    CONSTRAINT inventory_store_product_u UNIQUE (store_id, product_id)
);
